import Head from 'next/head'

export default function Home() {
  return (
    <div> 
      <Head>
        <title>Next.Js Crud App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='py-5'>
      <h1 className='text-xl md:text-5xl text-center font-bold py-10'>Müşteri Yönetimii</h1>
        <div className='container mx-auto flex justify-between py-5 border-b'>
          <div className='left flex gap-3'>

          </div>
        </div>
      </main>
    </div>
  )
}
